"""add_progress_step_to_analyses

Revision ID: a273730b5868
Revises: fdb28dcbea3a
Create Date: 2026-05-07 20:40:48.881960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a273730b5868'
down_revision: Union[str, Sequence[str], None] = 'fdb28dcbea3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('progress_step', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'progress_step')
    # ### end Alembic commands ###
